# Generated by Django 5.0.2 on 2024-03-08 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusinessOffer',
            new_name='Businesspdf',
        ),
        migrations.RenameField(
            model_name='businesspdf',
            old_name='offer',
            new_name='pdf',
        ),
    ]
